### ISSUE TITLE
Remove toolbar

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/dokuwiki-plugin-syntaxhighlighter3#11]
> Copied from [Plugin page](https://www.dokuwiki.org/plugin:syntaxhighlighter3)

Since in last version toolbar is not used more, is it possible to disable it by default? (Boris 2012-02-21)

> Modified shCore.js without toolbar : [shCore.js](http://db.tt/tOfPzsVS) (Boris 2012-02-22)
> 
> > I prefer to leave SyntaxHighlighter files and functionality untouched. Makes troubleshooting and maintenance easier.
> > 
> > I have considered adding a config setting for default options, but haven't done it because I think it would confuse the end users and it's probably not very easy to agree on what they should be, at least in an environment with a lot of users.
> > 
> > There's also an issue with disabling the toolbar while collapsing code, the code area will disappear completely.

**Comment by amazingBytes** [comment]
Had the same request. Additionally I wanted to change the default value of gutter from true to false.
I solved it by changing the file \lib\plugins\syntaxhighlighter3\action\action.php

At the end of that file i've inserted two lines of code just before the line
`ptln("  SyntaxHighlighter.all();");`

Now it reads
`ptln("  SyntaxHighlighter.defaults['gutter'] = false;");`
`ptln("  SyntaxHighlighter.defaults['toolbar'] = false;");`
`ptln("  SyntaxHighlighter.all();");`

**Comment by crazy-max** [comment]
Ok thanks, i will add your feature and an option in admin config to enable/disable toolbar and gutter

**Comment by amazingBytes** [comment]
That would be great! Thanls in advance

**Comment by crazy-max** [comment]
Solved on release 20160618
