### ISSUE TITLE
Optical issue

### ISSUE THREAD

**Issue by amazingBytes** [crazy-max/dokuwiki-plugin-syntaxhighlighter3#14]
Sometimes I'm using syntaxhighlighter3 within [WRAP-Boxes](https://www.dokuwiki.org/plugin:wrap).
But there is one ugly effect at the right side of the code block that could be improved by a simple alteration in the CSS files in `\lib\plugins\syntaxhighlighter3\sxh3\styles\`.

Here's a screenshot of the unimproved situation: ![sxh3_ugly](https://cloud.githubusercontent.com/assets/1564223/16172436/54000726-3589-11e6-9059-688dd89992af.png)
Line 56 of each CSS file should be commented out resulting in:
55: `.syntaxhighlighter {`
56: `/* width: 100% !important; */`
57: `margin: 1em 0 1em 0 !important;`
58: `position: relative !important;`
59: `overflow: auto !important;`
60: `font-size: 1em !important;`
61: `}`

Afterwards the code block within the WRAP looks like this: 
![sxh3_css_improved](https://cloud.githubusercontent.com/assets/1564223/16172439/9f10513a-3589-11e6-9e73-923039b6a5c2.png)

**Comment by crazy-max** [comment]
Cannot reproduce your issue.
Can you give me your DokuWiki version, WRAP Plugin version and a code example ?

For me :

```
<WRAP info>
<sxh text; toolbar: false; highlight: [9-18]>
# prefork MPM
# StartServers: number of server processes to start
# MinSpareServers: minimum number of server processes which are kept spare
# MaxSpareServers: maximum number of server processes which are kept spare
# MaxRequestWorkers: maximum number of server processes allowed to start
# MaxConnectionsPerChild: maximum number of requests a server process serves

<IfModule mpm_prefork_module>
        #StartServers           5
        #MinSpareServers                5
        #MaxSpareServers                10
        #MaxRequestWorkers      150
        #MaxConnectionsPerChild 0
        StartServers            2
        MinSpareServers         6
        MaxSpareServers         12
        MaxRequestWorkers       30
        MaxConnectionsPerChild  3000
</IfModule>
</sxh>
</WRAP>
```

Give :

![image2](https://cloud.githubusercontent.com/assets/1951866/16173213/718f826a-359a-11e6-90ff-56605d3b0685.png)

**Comment by amazingBytes** [comment]
DokuWiki version: Release 2015-08-10a "Detritus"
with default template
WRAP version: last updated on 2015-07-19 (just re-installed it for this test)

```
<WRAP info>
<sxh php>
  echo "quite simple example";
  echo "isn't it?";
</sxh>
</WRAP>
```

![wrap_sxh3](https://cloud.githubusercontent.com/assets/1564223/16173794/47ab0f88-35ad-11e6-8862-ad5914a0d90e.png)

**Comment by crazy-max** [comment]
Strange i'm on the same version of DokuWiki and WRAP version (from clean install btw). I think of a strange behaviour from an other plugin in your CSS.
You are on the [DokuWiki Template](https://www.dokuwiki.org/template:dokuwiki) right ?
Btw i have updated [the plugin to Syntaxhighlighter 3.0.90](https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter3/releases/tag/20160619) if you want to test.

**Comment by crazy-max** [comment]
Up?
