### ISSUE TITLE
print preview (and printed copy) garbled

### ISSUE THREAD

**Issue by jn0** [crazy-max/dokuwiki-plugin-syntaxhighlighter3#15]
Good idea (to drop formatting/prettifying), but poor result for overkill loosing EOLs and spaces:
![konsole-print-preview-bug](https://cloud.githubusercontent.com/assets/407437/16993550/ed7eac38-4eb4-11e6-9cd1-aa461c748cfc.png)

**Comment by crazy-max** [comment]
This plugin is not maintained anymore.
Check the new plugin : https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter4
