### ISSUE TITLE
403 Forbidden 

### ISSUE THREAD

**Issue by Danish22** [crazy-max/dokuwiki-plugin-syntaxhighlighter3#16]
Hi,
While using the demo code for syntaxhighlighter provided in readme page on Playground , When I click preview received the below error - 
**Forbidden
You don't have permission to access /doku.php on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.**

> PS:I already changed the permission to 0755 for all the files.

What should I do now?

**Comment by crazy-max** [comment]
Hi,

What is the full URL to your wiki ?
Maybe it's linked to your .htaccess config
Btw have you tried the new plugin (syntaxhighlighter4) ?

**Comment by Danish22** [comment]
@crazy-max 
Hello, Thank you for responding
The URL is Wikicoders.Org  , Yes I updated the plugin to the latest version.

**Comment by Danish22** [comment]
@crazy-max   the .htaccess file contains  this `
RewriteEngine on
RewriteCond %{HTTP_HOST} ^wikicoders\.daredevilcorp\.com$ [OR]
RewriteCond %{HTTP_HOST} ^www\.wikicoders\.daredevilcorp\.com$
RewriteRule ^/?$ "http\:\/\/wikicoders\.org" [R=301,L]

`

**Comment by crazy-max** [comment]
@Danish22 No i'm talking about the [dokuwiki-plugin-syntaxhighlighter4 plugin](https://www.dokuwiki.org/plugin:syntaxhighlighter4) on this repository : https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter4

**Comment by Danish22** [comment]
@crazy-max 
Hi this is what I am using 
![doku](https://cloud.githubusercontent.com/assets/8232132/21023630/599017ca-bda7-11e6-81fa-fcec3e6769d1.JPG)

**Comment by crazy-max** [comment]
So you are on the wrong repository
Please open a new issue on the good repository : https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter4
